### ISSUE TITLE
Set hostname need sudo privilege.

### ISSUE THREAD

**Issue by evshary** [Adlink-ROS/RMT_example#18]
Now setting hostname in agent side needs sudo privilege. However, if we use hostctl, it doesn't need sudo privilege.

**Comment by QQting** [comment]
hostnamectl needs privilege when your connection is via SSH

**Comment by evshary** [comment]
It seems like operations on hostname / wifi via SSH is not available. Maybe we should make sure if agent can modify hostname and wifi while it runs as daemon.

**Comment by evshary** [comment]
This is fixed via #26
